### Signup Request
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "burak",
  "password": "123"
}

### Login Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "burak",
  "password": "123"
}

### HealthCheck Request
GET http://localhost:8080/healthCheck
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJidXJhayIsImlzcyI6ImJ1cmFrZ3VsLmNvbS50ciIsImlhdCI6MTY1Nzg5NDY0NywiZXhwIjoxNjU3ODk0OTQ3fQ._8EUA5YPckRefiuYmHWz-eyy2VvPw63W1KKG7J8LsTlTkYFI7ibFvi96j-bidXa6IG0wYr--o4uaZY7xabUdgg